title: Sessions Module Documentation
description: This is a documentation portal for the Event.Rocks Platform's Sessions module!
theme: just-the-docs

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon-34.png"

url: https://eventicious.com/

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

heading_anchors: true

callouts:
  warning:
    title: Warning
    color: red

aux_links:
  Documentation Repository: https://github.com/egoranuchin/merk.team-test

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2024 Egor Anuchin."

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/egoranuchin/merk.team-test" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
